### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by C0rn3j** [Lyrics/lyrics#224]
At the moment some of the tests fail.

```
  1: for no filename extensions                      ok
  2: for no files in upper level dirs                ok
  3: for no directories in album dirs                ok
  4: for no triple dots within texts                 FAILED (database-tests.at:24)
  5: for no chorus within texts                      FAILED (database-tests.at:29)
  6: for no URLs within texts                        ok
  7: for no invalid unicode characters within texts  ok
  8: for no Windows-style EOLs within texts          ok
  9: for no empty files                              FAILED (database-tests.at:49)
 10: for no empty directories                        FAILED (database-tests.at:54)
 11: for no copyright sign within texts              FAILED (database-tests.at:59)
 12: for no spaces at end of line                    ok
```
-  [x] 4: for no triple dots within texts  - is it worth it to wage the war against triple dots? there's over a thousand occurrences (not affected files, most have multiple)
-  [x] 5: for no chorus within texts - 14 occurrences
-  [x] 6: for no URLs within texts - just two occurences with http://www.musictory.de/musik/Supershirt - I think we could just nip those straight away?
-  [x] 9: for no empty files - Seems to fail without useful logs
-  [x] 10: for no empty directories - Seems to fail without useful logs
-  [x] 11: for no copyright sign within texts - About 35 occurences and all of them are like `
/D/Damageplan/New Found Power/Breathing New Life:Copyright © Warner/Chappell Music, Inc` - how can these be rewritten? They are all similar/identical.

[Test log](https://haste.rys.pw/lasetuhame.diff)

**Comment by vflyson** [comment]
About triple dots, I think we could replace them with the unicode ellipsis character during the build time of the static website, and realistically nobody would bother replacing those "..." with "…", it'd only reduce the amount of contributions the database gets in the long run. I think your opinion regarding that test is right on.

**Comment by C0rn3j** [comment]
What's the point in replacing them with unicode? I thought you wanted them removed completely

**Comment by vflyson** [comment]
It may be my OCD, but basically there's a unicode ellipsis symbol available in most popular fonts, and using triple dots instead of that symbol is a common practice due to the complexity that it requires to put the ellipsis into the text (a combination of keys or copy-pasting it from somewhere). So I don't think it's a bad idea if in the "source" lyrics file it's triple dots, but during build time of the website we replace those triple dots with the appropriate unicode symbol.

But now I'm thinking that if lyrics get copied/scraped from the website, not the database, they will differ and contain that ellipsis symbol. It's a tricky situation, I'm now leaning towards accepting the fact that using triple dots for ellipsis may be the only realistic approach.
