### ISSUE TITLE
Quotation marks need refinement

### ISSUE THREAD

**Issue by snshn** [Lyrics/lyrics#363]
Here's a good reference https://smartquotesforsmartpeople.com/

@defanor do you think we should make a unit test for quotation marks, or rather change them when we build the website?

**Comment by defanor** [comment]
Not sure if either should be done, or can be done reliably at all (even
just for English-language lyrics). Usage of "proper" quotation (and
punctuation in general, including various dashes, ellipsis, whitespace
characters) looks silly when it's wrong, which tends to happen on
attempts to automatically "fix" it. Even a test to ensure that there's
no ASCII quotation characters (forcing humans to sort out the fancy
punctuation) would not be suitable for lyrics in Lojban, for instance,
and likely some other languages.

Maybe there should be a way to disable certain tests for certain files,
if we were to attempt dealing with natural languages, as well as to
define a locale per-file. Per-file spelling exceptions may be nice to
add too, so that everything could be spell checked. Possibly there even
are spell or grammar checkers capable of checking punctuation, so that
we won't end up implementing a custom one in the test suite.

**Comment by snshn** [comment]
Didn't think of various languages, you're right... the `Language  American`/`Language  Lojban` LMML could help here, will need to incorporate LMML parsing into tests at some point, perhaps come back to this after.
