### ISSUE TITLE
Unable to clone on Windows

### ISSUE THREAD

**Issue by thesobercoder** [Lyrics/lyrics#374]
`git clone https://github.com/thesobercoder/lyrics.git`

produces the following error

```
Cloning into 'lyrics'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 14457 (delta 2), reused 2 (delta 0), pack-reused 14447
Receiving objects: 100% (14457/14457), 2.50 MiB | 2.57 MiB/s, done.
Resolving deltas: 100% (7004/7004), done.
error: invalid path 'database/A/Adam Angst/Adam Angst/Wochenende. Saufen. Geil.'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

OS - Windows 10
Git - git version 2.25.0.windows.1

**Comment by snshn** [comment]
Hey there! Thank you for reporting this! I'm working on switching the CI pipeline of this project to GitHub Actions, will cover all 3 OSes, and the Windows part should cover the `git clone` scenario on NTFS/FAT32 filesystem. I agree that song/album/artist names within filenames can be altered to make it possible to store this database on popular filesystems that have certain limitations rather than in a SQL or any other kind of binary format. Metadata within each lyrics file should be enough for referencing original names.

**Comment by snshn** [comment]
This should be resolved now
