### ISSUE TITLE
Question about non-English artists and multi-artists song

### ISSUE THREAD

**Issue by mikelyou** [Lyrics/lyrics#379]
### Non-English artist

I noticed that the artists are arranged by their first character, and are saved in different folders from A to Z. 

But how about artist name starting with a non-Engish alphabet, e.g. `初音ミク`. This also applies to many other artists with the name in other languages. I think it needs a proper way to classify them.

The album name/song name/lyrics are fine with non-English words, from my understanding. So the only problem it the artist's name.

### Multi-artists song

Some songs have many artists, e.g. `Darker than Blood` by `Linkin Park` and `Steve Aoki`. Should the data be saved in one artist's folder or in some way?

***
Thank you so much for this project! Hope this project will be better and better. 😄 
And thank you for taking time to view this issue. 😄

**Comment by snshn** [comment]
Good day Mike,

### Non-English artist

I would think there should be created a directory that starts with `初` (or `ク`, if that's read from right-to-left), and put next to other directories. Separating by letters is mostly done for humans, to make the database easier to navigate by replicating how popular lyrics websites have their navigation implemented. I personally can't think of a better way to categorize things other than keep the whole database Unicode-friendly -- since it's planned to be international.

### Multi-artists song

[Here's an example](https://github.com/Lyrics/lyrics/blob/master/database/T/The%20Midnight/Nocturnal/River%20of%20Darkness#L45). The song is by "The Midnight (feat. Timecop1983)" -- two artists. Since it came out on The Midnight's album, not on Timecop1983's, it ends up only in The Midnight's directory. If both artists collaborate and release the same song on their two separate albums, then there should be two text files in the database, with the list of artists being flipped since the first artist should match the current album's artist, even if the song is exactly the same (I'll make a test for that).
Definitely no sym-links ever going to be used in this project.

---

It's been a couple of years of me and various contributors working on it, and it's only been improving. I mostly add songs I like myself, but also work on the structure and improving the Web UI whenever I have energy and inspiration to do so. Thank you for your questions, I'll form answers to them as ADRs and put them in the repo.

**Comment by mikelyou** [comment]
Thank you for the nice and detailed reply, it helps! 😄
(By the way, I'm new to Github and are still learning everything, I don't know when the issue should be closed, so please do that for me when it's time. I will try my best to contribute to this project in the future. )
