### ISSUE TITLE
url has weird behavior

### ISSUE THREAD

**Issue by chenrui333** [Lyrics/lyrics#533]
👋  it looks like this url has some weird behavior, `https://lyrics.github.io/db/p/portishead/dummy/roads`, while this url, `https://lyrics.github.io/db/P/Portishead/Dummy/Roads/` works perfectly fine for me.

![image](https://user-images.githubusercontent.com/1580956/103162384-f7664d80-47bd-11eb-86fe-295dc4569d50.png)

![image](https://user-images.githubusercontent.com/1580956/103162379-ec132200-47bd-11eb-8fbe-1fe7712b8760.png)

**Comment by chenrui333** [comment]
I was not an issue before (relates to https://github.com/Homebrew/homebrew-core/pull/67784)

**Comment by chenrui333** [comment]
also relates to https://github.com/Y2Z/monolith/pull/107/commits/8b1ebc7871c10c5e6a8154f8c7724f252d860e34

**Comment by andy5995** [comment]
@snshn 'https://lyrics.github.io/db/p/portishead/dummy/roads' When this url (with 'roads' in lowercase), is entered into the address bar, there is an infinite redirect. The URL keeps getting appended and the page tries to load. Then it happens again, and keeps repeating. Withing a few seconds, the URL in the address bar changes to:

```
https://lyrics.github.io/search.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=h.html?q=Portishead%20Dummy%20roads
```

and only stops when I hit ESC.

Thanks for the bug report @chenrui333

**Comment by snshn** [comment]
Thank you for the report! I promise one of these days I'm gonna get organizized and setup cypress.io to keep an eye on every part of the website.

The lower-cased URL was what the website used to have before we made it preserve the same case as on the filesystem.

The issue doesn't have much to do with Y2Z/monolith really, as that link stopped working once forced lower-casing was deprecated from lyrics.github.io. It's mostly related to Lyrics/lyrics-website-generator.

The redirect happens due to a basic JS snippet within 404 error page template that's intended to take the path, convert it into search query, and redirect to the search page in an attempt to find in the database what was requested via web address. Clever? Yes. Well done? Obviously not, there should be no infinite redirect loop. Should I fix it ASAP? Yes. Am I fixing it right now? You've guessed it!

**Comment by snshn** [comment]
Fixed! It works now, take a look: https://lyrics.github.io/db/p/portishead/dummy/roads

Thanks again for the report!
