### ISSUE TITLE
Directory Scheme For Artists With CJK Characters

### ISSUE THREAD

**Issue by Starman-x64** [Lyrics/lyrics#862]
Hi, I just wanted to get some clarification before I create a pull request with the lyrics I've added which for the songs of a Japanese artist/band which uses CJK characters in their name (`結束バンド`).

In [this closed issue](https://github.com/Lyrics/lyrics/issues/379#issue-660512353), @snshn said in regards to non-English artists (with the example of `初音ミク`) to
> [create] a directory that starts with `初` [...] and put next to [the] other directories.

Since (in Japanese) you can represent each of the thousands of [kanji characters](https://en.wikipedia.org/wiki/Kanji) and [46+25 katakana](https://en.wikipedia.org/wiki/Katakana) with the [46+25 hiragana](https://en.wikipedia.org/wiki/Hiragana), should I create a directory name with the hiragana character rather than the kanji character?
For example, for the artists `初音ミク`, `結束バンド`, `鈴木雅之`, and `すりぃ` (in hiragana: `はつねみく`, `けっそくばんど`, `すずきまさゆき`, `すりぃ`) would be sorted as:
```
...
X
Y
Z
あ
...
け
 /結束バンド
  /...
...
す
 /すりぃ
  /...
 /鈴木雅之
  /...
...
は
 /初音ミク
  /...
...
を
ん
が
...
ぺ
ぽ
```
I believe this is the way many other sites handle Japanese also, so it not only would condense potentially thousands of top-level directories with a few artists in them to only 46 (for Japanese), but it would also be easier to navigate for a Japanese user.

I'm not too sure about what to do for Korean and Chinese, however, but I decided to include them in this issue because these three languages all use [Chinese Characters](https://en.wikipedia.org/wiki/Chinese_characters) (although Korean hardly uses them any more so it would probably have a solution similar to Japanese with its [Hangul](https://en.wikipedia.org/wiki/Hangul)). Chinese artists would probably have to be listed using the Chinese character it starts with as Mandarin has no equivalent to hiragana of Hangul (aside from its pinyin romanisation, but it wouldn't make sense to list `費玉清` (Fei Yu-ching) under `F`.

Apologies for the long-ish issue, this is my first time doing stuff on someone else's repository so I just want to make sure I get everything right the first time :)

Edit: typos

**Comment by snshn** [comment]
Hello @Starman-x64 and thank you for such an elaborate description of the situation.
In all honesty, I think the decisions you've suggested to go with and the fact that that's how other lyrics sites do it, makes me think your solution is the optimal way to go, especially if it'd be more convenient to Japanese users.

The only experience I've had so far with Japanese artists was Akira Yamaoka, and his music is so popular because of Silent Hill games and movies, that it basically went straight under A/.

Since this database uses UTF-8 and is meant to be international, I'd say we'll need to just rely on sorting algorithms of file managers and programming languages to sort those letters properly, putting them side-by-side, and not creating any sub-directories for different alphabets.

The whole purpose of letter grouping is making sure we don't have to put too many directories side-by-side, and hence grouping and minimizing the amount of letters/groups used by every language in the database should be the way to go.

Last but not least, we could reorganize things later if the design turns out to be flawed, but it seems like what you've described is the best way to go, since it's the most user-friendly and compact way of grouping Japanese artists in this repository.

P.S.
I do not speak or read Chinese/Japanese/Korean, hence almost anybody who does, would be able to advise better on this matter.  Which seems like you were able to do quite well 😀

**Comment by Starman-x64** [comment]
Thanks for the reply! I'll submit the pull request now and get started on other Japanese songs too (if I can find them in my documents folder!). And as much as I wish I could, I can't understand Chinese or Korean either. I only know enough about them to know that they could raise some issues with the database structure. But hopefully someone who does know will come along with a fresh perspective on how to solve them! Speaking of which, should I close this issue now or wait until that someone arrives?

**Comment by snshn** [comment]
I think it can be closed now.  If there will ever be any issues with Chinese/Korean, we'll refer to this discuss and start a new issue if needed.  Thank you again.
